'use client';
import Nav from '../components/Nav';
import useLang from '../../lib/useLang';
import Link from 'next/link';

const T = {
  es:{titulo:'Consejos para viajar a Argentina',sub:'Todo lo que necesitas saber antes de llegar',btn:'Buscar anfitriones',cta:'Queres un anfitrion que te ayude a moverte por Argentina?',secciones:[{icon:'💵',titulo:'Dinero y divisas',items:['Trae dolares o euros en efectivo, es la mejor forma de cambiar.','En Argentina existe el dolar blue que da mejor cambio que el oficial.','Podes retirar pesos en cajeros Banelco con Wise o Revolut pagando comision minima.','No cambies en el aeropuerto, el tipo de cambio es muy desfavorable.','Los anfitriones de Knowan pueden orientarte sobre donde cambiar.']},{icon:'🚌',titulo:'Como moverse',items:['En Buenos Aires existe el subte, colectivos, trenes y taxis.','Para el transporte publico necesitas la tarjeta SUBE, se compra en kioscos.','Los buses interurbanos son excelentes, companias como Andesmar cubren todo el pais.','Uber, InDriver y Cabify son mas economicos que el taxi tradicional.']},{icon:'🍖',titulo:'Que comer',items:['El asado es el plato nacional, carne a las brasas que se come en familia.','Los alfajores son el snack mas popular, galletas rellenas de dulce de leche.','Las empanadas son perfectas para comer rapido.','El helado argentino es considerado uno de los mejores del mundo.','La milanesa es un clasico, carne empanada frita con papas fritas.']},{icon:'📱',titulo:'Conectividad y eSIM',items:['Recomendamos comprar una eSIM antes de llegar.','Holafly ofrece eSIM con datos ilimitados para Argentina.','Tambien podes comprar un chip local de Personal, Claro o Movistar.','El WiFi en hostels y cafes es generalmente bueno.']},{icon:'🔒',titulo:'Seguridad',items:['Argentina es un destino seguro para turistas.','Como en cualquier ciudad grande, cuidado con el celular en la via publica.','Usa bolsillo interior o rinonera para documentos y efectivo.','Los barrios Palermo, San Telmo y Recoleta son muy seguros.']}]},
  en:{titulo:'Travel tips for Argentina',sub:'Everything you need to know before you arrive',btn:'Find hosts',cta:'Want a host to help you get around Argentina?',secciones:[{icon:'💵',titulo:'Money and currency',items:['Bring USD or EUR in cash, best way to exchange at favorable rate.','Argentina has the blue dollar which gives a much better rate than official.','You can withdraw pesos at Banelco ATMs with Wise or Revolut.','Do not exchange at the airport, the rate is very unfavorable.','Knowan hosts can guide you on where to exchange safely.']},{icon:'🚌',titulo:'Getting around',items:['Buenos Aires has the subte, buses, trains and taxis.','To use public transport you need the SUBE card, buy it at kiosks.','Long-distance buses cover the whole country, companies like Andesmar.','Uber, InDriver and Cabify are cheaper than traditional taxis.']},{icon:'🍖',titulo:'What to eat',items:['Asado is the national dish, barbecued meat eaten with family.','Alfajores are the most popular snack, cookies filled with dulce de leche.','Empanadas are perfect for a quick meal.','Argentine ice cream is considered one of the best in the world.','Milanesa is a classic, breaded fried meat with french fries.']},{icon:'📱',titulo:'Connectivity and eSIM',items:['We recommend buying an eSIM before you arrive.','Holafly offers eSIM with unlimited data for Argentina.','You can also buy a local SIM from Personal, Claro or Movistar.','WiFi in hostels and cafes is generally good.']},{icon:'🔒',titulo:'Safety',items:['Argentina is a safe destination for tourists.','As in any big city, be careful with your phone in public.','Use an inner pocket for documents and cash.','Neighborhoods like Palermo, San Telmo and Recoleta are very safe.']}]},
  pt:{titulo:'Dicas para viajar para a Argentina',sub:'Tudo o que voce precisa saber',btn:'Encontrar anfitrioes',cta:'Quer um anfitriao para te ajudar?',secciones:[{icon:'💵',titulo:'Dinheiro e cambio',items:['Traga dolares ou euros em especie.','A Argentina tem o dolar blue com taxa melhor que a oficial.','Voce pode sacar pesos em caixas Banelco com Wise ou Revolut.','Nao troque no aeroporto.','Os anfitrioes do Knowan podem orientar.']},{icon:'🚌',titulo:'Como se locomover',items:['Buenos Aires tem metro, onibus, trens e taxis.','Para o transporte publico voce precisa do cartao SUBE.','Onibus de longa distancia cobrem todo o pais.','Uber, InDriver e Cabify sao mais baratos que taxi.']},{icon:'🍖',titulo:'O que comer',items:['O asado e o prato nacional.','Alfajores sao o lanche mais popular.','Empanadas sao perfeitas para comer rapido.','O sorvete argentino e um dos melhores do mundo.']},{icon:'📱',titulo:'Conectividade e eSIM',items:['Recomendamos comprar um eSIM antes de chegar.','Holafly oferece eSIM com dados ilimitados.','Tambem pode comprar chip local.']},{icon:'🔒',titulo:'Seguranca',items:['A Argentina e um destino seguro.','Cuidado com o celular em publico.','Use bolso interno para documentos.']}]},
  fr:{titulo:'Conseils pour voyager en Argentine',sub:'Tout ce que vous devez savoir',btn:'Trouver des hotes',cta:'Vous voulez un hote pour vous aider?',secciones:[{icon:'💵',titulo:'Argent et devises',items:["Apportez des USD ou EUR en especes.",'Le dollar bleu donne un meilleur taux.',"Retirez aux distributeurs Banelco avec Wise.",'Ne changez pas a aeroport.','Les hotes Knowan peuvent vous guider.']},{icon:'🚌',titulo:'Se deplacer',items:['Buenos Aires a le metro, bus, trains et taxis.','Vous avez besoin de la carte SUBE.','Les bus longue distance couvrent tout le pays.','Uber, InDriver et Cabify sont moins chers.']},{icon:'🍖',titulo:'Que manger',items:["L'asado est le plat national.",'Les alfajores sont le snack le plus populaire.','Les empanadas sont parfaites.',"La glace argentine est parmi les meilleures."]},{icon:'📱',titulo:'Connectivite et eSIM',items:["Achetez un eSIM avant d'arriver.",'Holafly propose des eSIM avec donnees illimitees.','Ou achetez une SIM locale.']},{icon:'🔒',titulo:'Securite',items:["L'Argentine est une destination sure.",'Faites attention au telephone en public.','Utilisez une poche interieure.']}]},
  it:{titulo:'Consigli per viaggiare in Argentina',sub:'Tutto quello che devi sapere',btn:'Trova host',cta:'Vuoi un host che ti aiuti?',secciones:[{icon:'💵',titulo:'Denaro e valute',items:['Porta USD o EUR in contanti.','Il dollaro blu da un tasso migliore.',"Preleva pesos agli ATM Banelco con Wise.",'Non cambiare in aeroporto.','Gli host di Knowan possono guidarti.']},{icon:'🚌',titulo:'Come spostarsi',items:['Buenos Aires ha metropolitana, autobus, treni e taxi.','Hai bisogno della carta SUBE.','Gli autobus a lunga percorrenza coprono tutto il paese.','Uber, InDriver e Cabify sono piu economici.']},{icon:'🍖',titulo:'Cosa mangiare',items:["L'asado e il piatto nazionale.",'Gli alfajores sono lo snack piu popolare.','Le empanadas sono perfette.','Il gelato argentino e tra i migliori al mondo.']},{icon:'📱',titulo:'Connettivita e eSIM',items:['Acquista un eSIM prima di arrivare.','Holafly offre eSIM con dati illimitati.','Puoi anche acquistare una SIM locale.']},{icon:'🔒',titulo:'Sicurezza',items:["L'Argentina e una destinazione sicura.",'Fai attenzione al telefono in pubblico.','Usa una tasca interna.']}]},
  de:{titulo:'Reisetipps fur Argentinien',sub:'Alles was Sie wissen mussen',btn:'Gastgeber finden',cta:'Mochten Sie einen Gastgeber der Ihnen hilft?',secciones:[{icon:'💵',titulo:'Geld und Wahrung',items:['Bringen Sie USD oder EUR in bar mit.','Der blaue Dollar gibt einen besseren Kurs.','Heben Sie Pesos an Banelco-Automaten mit Wise ab.','Tauschen Sie nicht am Flughafen.','Knowan-Gastgeber konnen Sie fuhren.']},{icon:'🚌',titulo:'Fortbewegung',items:['Buenos Aires hat U-Bahn, Busse, Zuge und Taxis.','Sie benotigen die SUBE-Karte.','Fernbusse decken das ganze Land ab.','Uber, InDriver und Cabify sind gunstiger.']},{icon:'🍖',titulo:'Was essen',items:['Asado ist das Nationalgericht.','Alfajores sind der beliebteste Snack.','Empanadas sind perfekt fur eine schnelle Mahlzeit.','Argentinisches Eis gilt als eines der besten.']},{icon:'📱',titulo:'Konnektivitat und eSIM',items:['Kaufen Sie eine eSIM vor der Ankunft.','Holafly bietet eSIM mit unbegrenzten Daten.','Oder kaufen Sie eine lokale SIM-Karte.']},{icon:'🔒',titulo:'Sicherheit',items:['Argentinien ist ein sicheres Reiseziel.','Passen Sie auf Ihr Telefon auf.','Verwenden Sie eine Innentasche.']}]},
  zh:{titulo:'阿根廷旅行贴士',sub:'到达前您需要了解的一切',btn:'寻找主人',cta:'想要一个主人帮助您吗？',secciones:[{icon:'💵',titulo:'金钱和货币',items:['带美元或欧元现金。','阿根廷有蓝色美元，比官方汇率好。','可以在Banelco自动取款机用Wise提取比索。','不要在机场兑换。','Knowan的主人可以指导您。']},{icon:'🚌',titulo:'交通出行',items:['布宜诺斯艾利斯有地铁、公共汽车、火车和出租车。','乘坐公共交通需要SUBE卡。','长途巴士覆盖全国各地。','Uber、InDriver和Cabify比传统出租车便宜。']},{icon:'🍖',titulo:'饮食',items:['阿萨多是国菜。','阿尔法霍尔是最受欢迎的零食。','恩帕纳达斯是快速用餐的完美选择。','阿根廷冰淇淋被认为是世界上最好的之一。']},{icon:'📱',titulo:'网络和eSIM',items:['建议在到达前购买eSIM。','Holafly提供阿根廷无限数据eSIM。','也可以在当地购买SIM卡。']},{icon:'🔒',titulo:'安全',items:['阿根廷是一个安全的旅游目的地。','在公共场所注意手机。','使用内袋存放证件和现金。']}]},
  ru:{titulo:'Советы для путешествия в Аргентину',sub:'Всё что нужно знать перед приездом',btn:'Найти хозяина',cta:'Хотите хозяина который поможет вам?',secciones:[{icon:'💵',titulo:'Деньги и валюта',items:['Привезите наличные USD или EUR.','В Аргентине есть синий доллар с лучшим курсом.','Можно снимать песо в банкоматах Banelco с Wise.','Не меняйте в аэропорту.','Хозяева Knowan могут подсказать.']},{icon:'🚌',titulo:'Передвижение',items:['В Буэнос-Айресе есть метро, автобусы, поезда и такси.','Для общественного транспорта нужна карта SUBE.','Междугородние автобусы охватывают всю страну.','Uber, InDriver и Cabify дешевле такси.']},{icon:'🍖',titulo:'Что поесть',items:['Асадо — национальное блюдо.','Альфахорес — самая популярная закуска.','Эмпанадас идеальны для перекуса.','Аргентинское мороженое одно из лучших.']},{icon:'📱',titulo:'Связь и eSIM',items:['Рекомендуем купить eSIM до приезда.','Holafly предлагает eSIM с безлимитным интернетом.','Также можно купить местную SIM.']},{icon:'🔒',titulo:'Безопасность',items:['Аргентина безопасное направление.','Следите за телефоном на улице.','Используйте внутренний карман.']}]},
};

export default function Consejos() {
  const { lang } = useLang();
  const t = T[lang] || T.en;

  return (
    <>
      <Nav links={[{href:'/explorar',label:t.btn}]} />
      <div className="container">
        <div className="card" style={{textAlign:'center',marginBottom:16}}>
          <div style={{fontSize:48,marginBottom:8}}>🇦🇷</div>
          <h1 style={{marginBottom:4}}>{t.titulo}</h1>
          <p style={{color:'#888',fontSize:14}}>{t.sub}</p>
        </div>
        {t.secciones.map((s, i) => (
          <div key={i} className="card" style={{marginBottom:16}}>
            <h2 style={{marginBottom:16}}>{s.icon} {s.titulo}</h2>
            <div style={{display:'flex',flexDirection:'column',gap:10}}>
              {s.items.map((item, j) => (
                <div key={j} style={{display:'flex',gap:10,alignItems:'flex-start'}}>
                  <span style={{color:'#4B6CB7',fontWeight:700,flexShrink:0}}>→</span>
                  <p style={{margin:0,fontSize:14,color:'#555',lineHeight:1.6}}>{item}</p>
                </div>
              ))}
            </div>
          </div>
        ))}
        <div className="card" style={{background:'#4B6CB7',textAlign:'center'}}>
          <p style={{color:'white',fontSize:15,marginBottom:16}}>{t.cta}</p>
          <Link href="/explorar">
            <button className="btn-orange" style={{width:'auto',padding:'12px 28px'}}>{t.btn}</button>
          </Link>
        </div>
      </div>
    </>
  );
}
